# Generated by Django 4.0.6 on 2022-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
