# Generated by Django 4.0.6 on 2022-08-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_id_alter_dishescategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImageCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restaurantimagecategory'),
        ),
    ]
