# Generated by Django 4.0.6 on 2022-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dish_description_dish_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
