# Generated by Django 4.0.6 on 2022-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_remove_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='front_end_key',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
